config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :listings

  root 'listings#index'

end

app/models/listing.rb
class Listing < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  def index
    @listings = Listing.all
  end

  def show
    @listing = Listing.find(params[:id])
  end

  def new
    @listing = Listing.new
  end

  def edit
    @listing = Listing.find(params[:id])
  end

  def create
    @listing = Listing.new(listing_params)

    if @listing.save
      redirect_to @listing
    else
      render 'new'
    end
  end

  def update
    @listing = Listing.find(params[:id])

    if @listing.update(listing_params)
      redirect_to @listing
    else
      render 'edit'
    end
  end

private
  def listing_params
    params.require(:listing).permit(:title, :text)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listing_helper.rb
module ListingHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Huthunt
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  = render 'shared/header'

  %body{:class => "#{controller_name}", :id => "#{action_name}"}
    = yield

app/views/listings/_form.html.haml
= form_for @listing do |f|
  - if @listing.errors.any?
    #error_explanation
      %h2
        = pluralize(@listing.errors.count, "error")
        prohibited
        this listing from being saved:
      %ul
        - @listing.errors.full_messages.each do |msg|
          %li= msg
  %p
    = f.label :title
    %br/
    = f.text_field :title
  %p
    = f.label :text
    %br/
    = f.text_area :text
  %p
    = f.submit

app/views/listings/edit.html.haml
= render 'form'

app/views/listings/index.html.haml
%section.intro.padded
  .browse
    = link_to 'Browse', root_path(anchor: "listings"), :class => 'smoothScroll button'
  .list
    = link_to 'New listing', new_listing_path, :class => 'button'

%section
  %ul.listings#listings
    - @listings.each do |listing|
      %a.listing{:href => listing_path(listing)}
        %li
          %h3=listing.title
          %p=listing.text

app/views/listings/new.html.haml
= render 'form'

app/views/listings/show.html.haml
%p
  %strong Title:
  = @listing.title
%p
  %strong Text:
  = @listing.text

= link_to 'Edit', edit_listing_path(@listing)

app/views/shared/_header.html.haml
%header
  -if current_user
    = link_to('Logout', destroy_user_session_path, :method => :delete, :class => 'button')
  -else
    = link_to('Login', new_user_session_path, :class => 'button')